services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc-frontend-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5005:5005'
    environment:
      - NODE_ENV=development
    restart: unless-stopped