// Mock data for all services - used as fallback when API calls fail

// Dashboard Mock Data
export const mockDashboardData = {
  overview: {
    totalEarnings: 2450.75,
    totalReferrals: 12,
    activeDownlines: 8,
    pendingPayouts: 320.50,
    recentActivity: [
      {
        id: "1",
        type: "commission" as const,
        description: "Direct commission from CryptoQueen",
        amount: 45.20,
        timestamp: "2024-01-15T10:30:00Z",
        status: "completed" as const,
      },
      {
        id: "2",
        type: "referral" as const,
        description: "New downline joined: NFTNinja",
        amount: undefined,
        timestamp: "2024-01-14T15:45:00Z",
        status: "completed" as const,
      },
      {
        id: "3",
        type: "purchase" as const,
        description: "GCC4 POWERSTAR #1234 purchased",
        amount: 2.5,
        timestamp: "2024-01-13T09:20:00Z",
        status: "completed" as const,
      },
    ],
  },
  stats: {
    monthlyEarnings: 850.25,
    monthlyGrowth: 12.5,
    totalNetworkSize: 45,
    successRate: 94.2,
  },
  immediateDownlines: [
    {
      id: "down1",
      nickname: "CryptoQueen",
      revenue: 1250.75,
      status: "active" as const,
      rank: "SILVER",
    },
    {
      id: "down2", 
      nickname: "DeFiDude",
      revenue: 890.50,
      status: "active" as const,
      rank: "GOLD",
    },
    {
      id: "down3",
      nickname: "TokenTrader", 
      revenue: 567.25,
      status: "active" as const,
      rank: "BRONZE",
    },
    {
      id: "down4",
      nickname: "NFTNinja",
      revenue: 432.80,
      status: "inactive" as const,
      rank: "SILVER",
    },
  ],
  charts: {
    purchasesOverTime: [
      { date: "Jan 1", purchases: 3, volume: 45.2 },
      { date: "Jan 2", purchases: 2, volume: 32.8 },
      { date: "Jan 3", purchases: 5, volume: 67.5 },
      { date: "Jan 4", purchases: 7, volume: 89.1 },
      { date: "Jan 5", purchases: 4, volume: 56.3 },
      { date: "Jan 6", purchases: 9, volume: 123.7 },
      { date: "Jan 7", purchases: 8, volume: 98.4 },
      { date: "Jan 8", purchases: 6, volume: 76.2 },
      { date: "Jan 9", purchases: 11, volume: 145.8 },
      { date: "Jan 10", purchases: 7, volume: 92.1 },
      { date: "Jan 11", purchases: 5, volume: 68.9 },
      { date: "Jan 12", purchases: 10, volume: 134.5 },
      { date: "Jan 13", purchases: 8, volume: 112.3 },
      { date: "Jan 14", purchases: 12, volume: 167.8 },
    ],
    commissionSources: [
      { name: "C1", value: 45.2, color: "#00E5FF" },
      { name: "C2", value: 32.8, color: "#00FFC8" },
      { name: "C3", value: 18.5, color: "#6F00FF" },
    ],
    commissionBreakdown: [
      { month: "Jan", c1: 45.2, c2: 32.8, c3: 18.5, bonuses: 12.3 },
      { month: "Feb", c1: 52.1, c2: 38.9, c3: 22.1, bonuses: 15.7 },
      { month: "Mar", c1: 48.7, c2: 35.2, c3: 20.8, bonuses: 13.9 },
      { month: "Apr", c1: 61.3, c2: 44.6, c3: 26.9, bonuses: 18.2 },
      { month: "May", c1: 55.8, c2: 41.2, c3: 24.3, bonuses: 16.5 },
      { month: "Jun", c1: 67.4, c2: 49.8, c3: 29.1, bonuses: 19.8 },
    ],
    networkGrowth: [
      { date: "Jan 1", totalMembers: 12, activeMembers: 10, newReferrals: 2 },
      { date: "Jan 2", totalMembers: 13, activeMembers: 11, newReferrals: 1 },
      { date: "Jan 3", totalMembers: 15, activeMembers: 13, newReferrals: 2 },
      { date: "Jan 4", totalMembers: 18, activeMembers: 15, newReferrals: 3 },
      { date: "Jan 5", totalMembers: 20, activeMembers: 17, newReferrals: 2 },
      { date: "Jan 6", totalMembers: 23, activeMembers: 19, newReferrals: 3 },
      { date: "Jan 7", totalMembers: 25, activeMembers: 21, newReferrals: 2 },
      { date: "Jan 8", totalMembers: 27, activeMembers: 23, newReferrals: 2 },
      { date: "Jan 9", totalMembers: 30, activeMembers: 25, newReferrals: 3 },
      { date: "Jan 10", totalMembers: 32, activeMembers: 27, newReferrals: 2 },
      { date: "Jan 11", totalMembers: 34, activeMembers: 29, newReferrals: 2 },
      { date: "Jan 12", totalMembers: 37, activeMembers: 31, newReferrals: 3 },
      { date: "Jan 13", totalMembers: 39, activeMembers: 33, newReferrals: 2 },
      { date: "Jan 14", totalMembers: 42, activeMembers: 35, newReferrals: 3 },
    ],
  },
}

// Network Mock Data
export const mockNetworkData = {
  structure: {
    currentUser: {
      id: "current",
      nickname: "YOU",
      anonymizedEmail: "y*****@gmail.com",
      level: 0,
      joinDate: "2023-06-15",
      rank: "GOLD",
      isActive: true,
      totalReferrals: 12,
    },
    sponsor: {
      id: "sponsor1",
      name: "SARAH JOHNSON",
      username: "sarahj",
      level: 1,
      joinDate: "2023-05-10",
      rank: "PLATINUM",
      isActive: true,
      totalReferrals: 45,
    },
    downlines: [
      {
        id: "down1",
        nickname: "CryptoQueen",
        anonymizedEmail: "c*****@gmail.com",
        level: 1,
        joinDate: "2023-07-20",
        rank: "SILVER",
        isActive: true,
        totalReferrals: 8,
        children: [
          {
            id: "down1-1",
            nickname: "BlockchainBuddy",
            anonymizedEmail: "b*****@yahoo.com",
            level: 2,
            joinDate: "2023-08-15",
            rank: "BRONZE",
            isActive: true,
            totalReferrals: 3,
          },
          {
            id: "down1-2",
            nickname: "NFTNinja",
            anonymizedEmail: "n*****@hotmail.com",
            level: 2,
            joinDate: "2023-09-01",
            rank: "SILVER",
            isActive: false,
            totalReferrals: 5,
          },
        ],
      },
      {
        id: "down2",
        nickname: "DeFiDude",
        anonymizedEmail: "d*****@outlook.com",
        level: 1,
        joinDate: "2023-08-05",
        rank: "GOLD",
        isActive: true,
        totalReferrals: 15,
        children: [
          {
            id: "down2-1",
            nickname: "Web3Wizard",
            anonymizedEmail: "w*****@protonmail.com",
            level: 2,
            joinDate: "2023-09-10",
            rank: "BRONZE",
            isActive: true,
            totalReferrals: 2,
          },
        ],
      },
      {
        id: "down3",
        nickname: "TokenTrader",
        anonymizedEmail: "t*****@icloud.com",
        level: 1,
        joinDate: "2023-09-15",
        rank: "BRONZE",
        isActive: true,
        totalReferrals: 1,
      },
    ],
  },
  stats: {
    totalDownlines: 6,
    activeMembers: 5,
    totalReferrals: 29,
    networkDepth: 2,
    monthlyGrowth: 8.5,
  },
}

// Commission Mock Data
export const mockCommissionData = {
  history: [
    {
      id: "1",
      transactionId: "b1a7e8c2-1f2d-4e3a-9c1b-1a2b3c4d5e6f",
      date: "2024-01-15",
      amount: 45.20,
      type: "direct" as const,
      source: "CryptoQueen",
      status: "completed" as const,
      description: "Direct commission from level 1 downline",
      currency: "USDC",
    },
    {
      id: "2",
      transactionId: "c2b8f9d3-2e3f-5a4b-8d2c-2b3c4d5e6f7a",
      date: "2024-01-14",
      amount: 32.80,
      type: "indirect" as const,
      source: "BlockchainBuddy",
      status: "completed" as const,
      description: "Indirect commission from level 2 downline",
      currency: "USDC",
    },
    {
      id: "3",
      transactionId: "d3c9g0e4-3f4g-6b5c-9e3d-3c4d5e6f7a8b",
      date: "2024-01-13",
      amount: 67.50,
      type: "bonus" as const,
      source: "System",
      status: "completed" as const,
      description: "Monthly performance bonus",
      currency: "USDC",
    },
    {
      id: "4",
      transactionId: "e4d0h1f5-4g5h-7c6d-0f4e-4d5e6f7a8b9c",
      date: "2024-01-12",
      amount: 23.40,
      type: "direct" as const,
      source: "DeFiDude",
      status: "pending" as const,
      description: "Direct commission from level 1 downline",
      currency: "USDC",
    },
    {
      id: "5",
      transactionId: "f5e1i2g6-5h6i-8d7e-1g5f-5e6f7a8b9c0d",
      date: "2024-01-11",
      amount: 18.90,
      type: "indirect" as const,
      source: "Web3Wizard",
      status: "failed" as const,
      description: "Indirect commission from level 2 downline",
      currency: "USDC",
    },
  ],
  earnings: {
    totalEarnings: 2450.75,
    monthlyEarnings: 850.25,
    weeklyEarnings: 189.40,
    dailyEarnings: 45.20,
    currency: "USDC",
  },
  pending: [
    {
      id: "1",
      amount: 23.40,
      expectedDate: "2024-01-20",
      type: "Direct Commission",
      source: "DeFiDude",
      currency: "USDC",
    },
    {
      id: "2",
      amount: 15.80,
      expectedDate: "2024-01-22",
      type: "Indirect Commission",
      source: "NFTNinja",
      currency: "USDC",
    },
  ],
  stats: {
    totalCommissions: 2450.75,
    totalWithdrawals: 1800.50,
    pendingAmount: 39.20,
    successRate: 94.2,
    averageCommission: 45.20,
    monthlyGrowth: 12.5,
  },
  chartData: [
    { date: "Jan 1", earnings: 45.2, commissions: 3, withdrawals: 0 },
    { date: "Jan 2", earnings: 32.8, commissions: 2, withdrawals: 0 },
    { date: "Jan 3", earnings: 67.5, commissions: 5, withdrawals: 0 },
    { date: "Jan 4", earnings: 89.1, commissions: 7, withdrawals: 0 },
    { date: "Jan 5", earnings: 56.3, commissions: 4, withdrawals: 0 },
    { date: "Jan 6", earnings: 123.7, commissions: 9, withdrawals: 0 },
    { date: "Jan 7", earnings: 98.4, commissions: 8, withdrawals: 0 },
  ],
}

// Purchases Mock Data
export const mockPurchasesData = {
  history: [
    {
      id: "1",
      date: "2024-01-15",
      tokenId: "GCC4 POWERSTAR #1234",
      amount: 2.5,
      status: "completed" as const,
      currency: "USDC",
      source: "OpenSea",
    },
    {
      id: "2",
      date: "2024-01-14",
      tokenId: "GCC1 POWERSTAR #5678",
      amount: 1.8,
      status: "completed" as const,
      currency: "USDT",
      source: "Rarible",
    },
    {
      id: "3",
      date: "2024-01-13",
      tokenId: "GCC1 SUPRASTAR #9999",
      amount: 3.2,
      status: "pending" as const,
      currency: "USDT",
      source: "Foundation",
    },
    {
      id: "4",
      date: "2024-01-12",
      tokenId: "GCC3 POWERSTAR #4567",
      amount: 1.5,
      status: "completed" as const,
      currency: "USDT",
      source: "SuperRare",
    },
    {
      id: "5",
      date: "2024-01-11",
      tokenId: "GCC3 POWERSTAR #7890",
      amount: 4.1,
      status: "failed" as const,
      currency: "USDC",
      source: "OpenSea",
    },
    {
      id: "6",
      date: "2024-01-10",
      tokenId: "GCC2 POWERSTAR #2345",
      amount: 2.8,
      status: "completed" as const,
      currency: "USDT",
      source: "Async Art",
    },
    {
      id: "7",
      date: "2024-01-09",
      tokenId: "GCC1 SUPRASTAR #6789",
      amount: 5.2,
      status: "completed" as const,
      currency: "USDC",
      source: "Foundation",
    },
    {
      id: "8",
      date: "2024-01-08",
      tokenId: "GCC4 POWERSTAR#3456",
      amount: 1.9,
      status: "pending" as const,
      currency: "USDC",
      source: "Rarible",
    },
  ],
  overview: {
    totalSpent: 23.0,
    totalPurchases: 8,
    successRate: 75.0,
    averagePurchase: 2.875,
    currency: "USDC",
  },
  stats: {
    totalVolume: 23.0,
    monthlyVolume: 23.0,
    weeklyVolume: 8.5,
    dailyVolume: 2.5,
    totalTransactions: 8,
    successRate: 75.0,
    averageTransaction: 2.875,
    monthlyGrowth: 15.2,
  },
  chartData: [
    { date: "Jan 1", purchases: 12, volume: 2.4 },
    { date: "Jan 2", purchases: 8, volume: 1.8 },
    { date: "Jan 3", purchases: 15, volume: 3.2 },
    { date: "Jan 4", purchases: 22, volume: 4.1 },
    { date: "Jan 5", purchases: 18, volume: 3.5 },
    { date: "Jan 6", purchases: 25, volume: 5.2 },
    { date: "Jan 7", purchases: 30, volume: 6.8 },
    { date: "Jan 8", purchases: 28, volume: 6.1 },
    { date: "Jan 9", purchases: 35, volume: 7.5 },
    { date: "Jan 10", purchases: 32, volume: 7.2 },
    { date: "Jan 11", purchases: 40, volume: 8.9 },
    { date: "Jan 12", purchases: 38, volume: 8.3 },
    { date: "Jan 13", purchases: 45, volume: 9.6 },
    { date: "Jan 14", purchases: 42, volume: 9.1 },
  ],
}

// Payouts Mock Data
export const mockPayoutsData = {
  history: [
    {
      id: "1",
      date: "2024-01-15",
      amount: 500.00,
      status: "completed" as const,
      method: "Bank Transfer",
      currency: "USDC",
      transactionHash: "0x1234567890abcdef",
    },
    {
      id: "2",
      date: "2024-01-10",
      amount: 250.00,
      status: "completed" as const,
      method: "Crypto Wallet",
      currency: "USDC",
      transactionHash: "0xabcdef1234567890",
    },
    {
      id: "3",
      date: "2024-01-05",
      amount: 750.00,
      status: "pending" as const,
      method: "Bank Transfer",
      currency: "USDC",
    },
    {
      id: "4",
      date: "2024-01-01",
      amount: 300.00,
      status: "rejected" as const,
      method: "Crypto Wallet",
      currency: "USDC",
      notes: "Invalid wallet address",
    },
  ],
  pending: [
    {
      id: "1",
      amount: 750.00,
      requestDate: "2024-01-05",
      expectedDate: "2024-01-20",
      method: "Bank Transfer",
      currency: "USDC",
      status: "pending" as const,
    },
    {
      id: "2",
      amount: 320.50,
      requestDate: "2024-01-12",
      expectedDate: "2024-01-25",
      method: "Crypto Wallet",
      currency: "USDC",
      status: "processing" as const,
    },
  ],
  stats: {
    totalPayouts: 1800.50,
    totalAmount: 1800.50,
    pendingAmount: 1070.50,
    successRate: 85.7,
    averagePayout: 450.13,
    monthlyGrowth: 8.3,
  },
  chartData: [
    { date: "Jan 1", payouts: 2, amount: 300.0 },
    { date: "Jan 2", payouts: 1, amount: 150.0 },
    { date: "Jan 3", payouts: 3, amount: 450.0 },
    { date: "Jan 4", payouts: 2, amount: 400.0 },
    { date: "Jan 5", payouts: 1, amount: 750.0 },
    { date: "Jan 6", payouts: 4, amount: 600.0 },
    { date: "Jan 7", payouts: 2, amount: 350.0 },
  ],
}

// Utility function to simulate API delay
export const simulateApiDelay = (ms: number = 2000): Promise<void> => {
  return new Promise(resolve => setTimeout(resolve, ms))
} 